internal static class ApplicationDbContextHelpers
{
    /// <summary>
    /// Configures the model builder for the application database context.
    /// </summary>
    /// <param name="modelBuilder">The model builder.</param>
    public static void DatabaseModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Department>(entity =>
        {
            // Set properties for the entity
            entity.Property(e => e.Id).ValueGeneratedNever(); // Id is never generated by the database
            entity.Property(e => e.CreatedBy).HasMaxLength(100); // Maximum length of CreatedBy property
            entity.Property(e => e.LastModifiedBy).HasMaxLength(100); // Maximum length of LastModifiedBy property
            entity.OwnsOne(e => e.Name, name =>
            {
                name.Property(n => n.Value)
                    .HasColumnName("Name")
                    .HasMaxLength(250)
                    .IsRequired();
                name.HasIndex(n => n.Value).IsUnique();
            });
        });

        // Configure Employee entity
        modelBuilder.Entity<Employee>(entity =>
        {
            // Create index for PositionId property
            entity.HasIndex(e => e.PositionId, "IX_Employees_PositionId");
            // Create index for DepartmentId property
            entity.HasIndex(e => e.DepartmentId, "IX_Employees_DepartmentId");

            // Set properties for the entity
            entity.Property(e => e.Id).ValueGeneratedNever(); // Id is never generated by the database
            entity.Property(e => e.CreatedBy).HasMaxLength(100); // Maximum length of CreatedBy property
            entity.Property(e => e.Email).HasMaxLength(250); // Maximum length of Email property
            entity.Property(e => e.EmployeeNumber).HasMaxLength(100); // Maximum length of EmployeeNumber property
            entity.Property(e => e.LastModifiedBy).HasMaxLength(100); // Maximum length of LastModifiedBy property
            entity.Property(e => e.Phone).HasMaxLength(100); // Maximum length of Phone property
            entity.Property(e => e.Salary).HasColumnType("decimal(18, 2)"); // Salary is a decimal with precision 18 and scale 2
            entity.Property(e => e.Prefix).HasMaxLength(100); // Maximum length of Prefix property

            entity.OwnsOne(e => e.Name, name =>
            {
                name.Property(n => n.FirstName)
                    .HasColumnName("FirstName")
                    .HasMaxLength(100)
                    .IsRequired();
                name.Property(n => n.MiddleName)
                    .HasColumnName("MiddleName")
                    .HasMaxLength(100);
                name.Property(n => n.LastName)
                    .HasColumnName("LastName")
                    .HasMaxLength(100)
                    .IsRequired();
            });

            // Configure relationship between Employee and Position entities
            entity.HasOne(d => d.Position).WithMany(p => p.Employees).HasForeignKey(d => d.PositionId);
            // Configure relationship between Employee and Department entities (home org)
            entity.HasOne(d => d.Department)
                .WithMany()
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        // Configure Position entity
        modelBuilder.Entity<Position>(entity =>
        {
            // Create index for DepartmentId property
            entity.HasIndex(e => e.DepartmentId, "IX_Positions_DepartmentId");

            // Create index for SalaryRangeId property
            entity.HasIndex(e => e.SalaryRangeId, "IX_Positions_SalaryRangeId");

            // Set properties for the entity
            entity.Property(e => e.Id).ValueGeneratedNever(); // Id is never generated by the database
            entity.Property(e => e.CreatedBy).HasMaxLength(100); // Maximum length of CreatedBy property
            entity.Property(e => e.LastModifiedBy).HasMaxLength(100); // Maximum length of LastModifiedBy property
            entity.Property(e => e.PositionDescription)
                .IsRequired()
                .HasMaxLength(1000); // Required and maximum length of PositionDescription property
            entity.Property(e => e.PositionNumber)
                .IsRequired()
                .HasMaxLength(100); // Required and maximum length of PositionNumber property
            entity.OwnsOne(e => e.PositionTitle, title =>
            {
                title.Property(t => t.Value)
                    .HasColumnName("PositionTitle")
                    .HasMaxLength(250)
                    .IsRequired();
                title.HasIndex(t => t.Value).IsUnique();
            });

            // Configure relationship between Position and Department entities
            entity.HasOne(d => d.Department).WithMany(p => p.Positions).HasForeignKey(d => d.DepartmentId);

            // Configure relationship between Position and SalaryRange entities
            entity.HasOne(d => d.SalaryRange).WithMany(p => p.Positions).HasForeignKey(d => d.SalaryRangeId);
        });

        // Configure SalaryRange entity
        modelBuilder.Entity<SalaryRange>(entity =>
        {
            // Set properties for the entity
            entity.Property(e => e.Id).ValueGeneratedNever(); // Id is never generated by the database
            entity.Property(e => e.CreatedBy).HasMaxLength(100); // Maximum length of CreatedBy property
            entity.Property(e => e.Name).HasMaxLength(250); // Maximum length of Name property
            entity.Property(e => e.LastModifiedBy).HasMaxLength(100); // Maximum length of LastModifiedBy property
            entity.Property(e => e.MaxSalary).HasColumnType("decimal(18, 2)"); // MaxSalary is a decimal with precision 18 and scale 2
            entity.Property(e => e.MinSalary).HasColumnType("decimal(18, 2)"); // MinSalary is a decimal with precision 18 and scale 2
        });
    }
}
